app/main/api/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('article/', views.ArticleView.as_view(), name='article_list'),
    path('service/', views.ServiceView.as_view(), name='service_list'),
]

app/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('hcw/', views.HCWHomeView.as_view(), name='hcw_home'),
    path('about-us/', views.AboutUsView.as_view(), name='about_us'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('testimony/', views.TestimonyView.as_view(), name='testimony'),
    path('blog/', views.BlogView.as_view(), name='blog'),
    path('hcw-blog/', views.HcwBlogView.as_view(), name='hcw_blog'),
    path('count-blog/<int:pk>/', views.CountBlogView.as_view(), name='count_blog'),
    path('blog-detail/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('hcw-blog-detail/<int:pk>/', views.HcwBlogDetailView.as_view(), name='hcw_blog_detail'),
    path('category-info/<int:pk>', views.CategoryDetailView.as_view(),
         name='category_information'),
     path('hcw-category-info/<int:pk>', views.HcwCategoryDetailView.as_view(),
         name='hcw_category_information'),
    path('services/', views.ServiceView.as_view(), name='service_list'),
    path('testimony-detail/<int:pk>/',
         views.TestimonyDetailView.as_view(), name='testimony_detail'),
    path('privacy-policy/', views.PrivacyPolicy.as_view(), name='privacy_policy'),
]

huru/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('', include('app.main.urls', namespace='main')),
    path('api/', include('app.main.api.urls', namespace='main_api')),
    path('auth/', include('app.user.urls')),
    path('admin/', include('app.huru_admin.urls')),
    path('super-admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Huru adminstration'
admin.site.site_title = 'Huru'

app/main/models.py
from embed_video.fields import EmbedVideoField
from django.contrib.auth.models import Group
from resizeimage import resizeimage
from django.core.files import File
from app.user.models import User
from datetime import datetime
from django.db import models
from io import BytesIO
from PIL import Image
import sys
import os


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    sw_name = models.CharField(max_length=255, unique=True, blank=True, null=True)
    active = models.BooleanField(default=True)
    added_by = models.ForeignKey(
        User, related_name='user_category', on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'
        ordering = ['-id']
        verbose_name_plural = 'categories'

    def pwud_article_list(self):
        return self.category_article.filter(belong_to__name='pwud')

    def hcw_article_list(self):
        return self.category_article.filter(belong_to__name='hcw')


class Article(models.Model):
    user = models.ForeignKey(
        User, related_name='user_article', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    sw_title = models.CharField(max_length=100, blank=True, null=True)
    cover_photo = models.ImageField(upload_to='cover_photo')
    display_cover_photo_on_view_article = models.BooleanField(default=True)
    is_image_compressed = models.BooleanField(default=False)
    content = models.TextField()
    sw_content = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='category_article', blank=True, null=True)
    belong_to = models.ForeignKey(
        Group, related_name='article_belong_to', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    views = models.PositiveIntegerField(default=0)

    # calling image compression function before saving the data
    def save(self, *args, **kwargs):
        if self.is_image_compressed == False:
            new_image = self.compress(self.cover_photo)
            self.cover_photo = new_image
            self.is_image_compressed = True
        super().save(*args, **kwargs)

    # image compression method
    def compress(self, filename):
        im = Image.open(filename)

        im = im.convert('RGB')

        # get filename extension
        name, ext = os.path.splitext(filename.name)

        ''' new filename '''
        # current date and time
        now = datetime.now()
        timestamp = datetime.timestamp(now)
        new_name = name + str(timestamp)
        new_name = new_name.replace('.', '')

        new_filename = new_name+ext

        # check image size
        width = im.size[0]
        height = im.size[1]

        aspect = width / float(height)

        ideal_width = 800
        ideal_height = 800

        ideal_aspect = ideal_width / float(ideal_height)

        if aspect > ideal_aspect:
            # Then crop the left and right edges:
            new_width = int(ideal_aspect * height)
            offset = (width - new_width) / 2
            resize = (offset, 0, width - offset, height)
        else:
            # ... crop the top and bottom:
            new_height = int(width / ideal_aspect)
            offset = (height - new_height) / 2
            resize = (0, offset, width, height - offset)

        im = im.crop(resize).resize(
            (ideal_width, ideal_height), Image.ANTIALIAS)

        im_io = BytesIO()

        im.save(im_io, 'JPEG', quality=90)
        new_image = File(im_io, name=new_filename)
        return new_image

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return '{}'.format(self.title)


class Testimony(models.Model):
    title = models.CharField(max_length=255)
    url = EmbedVideoField()
    content = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=True)
    date_posted = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'Testimony'

    def __str__(self):
        return '{}'.format(self.title)


class Service(models.Model):
    facility = models.CharField(max_length=255)
    facility_type = models.CharField(max_length=255)
    service_offered = models.TextField()
    contact = models.CharField(max_length=17)
    region = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    location = models.CharField(max_length=100)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.facility

app/main/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import ArticleSerializer, ServiceSerializer
from rest_framework import generics
from app.main.models import Article, Service


class ArticleView(generics.ListAPIView):
    serializer_class = ArticleSerializer

    def get_queryset(self):

        return Article.objects.filter(active=True, belong_to__name='pwud')


class ServiceView(generics.ListAPIView):
    queryset = Service.objects.all()
    serializer_class = ServiceSerializer

app/main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from app.main.models import Article, Category, Testimony, Service
from django.views.generic.detail import DetailView
from django.utils.translation import gettext as _
from django.utils import translation
from django.utils.translation import get_language
from django.db.models import Q
from django.urls import reverse
from django.shortcuts import get_object_or_404


class HomeView(View):
    template_name = 'main/home.html'

    def get(self, request, *args, **kwargs):

        # x = get_language()
        # print('language used is = ', x)

        context = {}
        context['title'] = 'Huru'
        # context['hello'] = _('hello')
        context['posts'] = Article.objects.filter(
            active=True, belong_to__name='pwud')
        context['service_number'] = Service.objects.all().count()
        context['testimonies'] = Testimony.objects.all()
        return render(request, self.template_name, context)


class HCWHomeView(View):
    template_name = 'main/hcw_home.html'

    def get(self, request, *args, **kwargs):

        context = {}
        context['title'] = 'Huru'
        context['posts'] = Article.objects.filter(
            active=True, belong_to__name='hcw')
        # context['service_number'] = Service.objects.all().count()
        # context['testimonies'] = Testimony.objects.all()
        return render(request, self.template_name, context)


class AboutUsView(View):
    template_name = 'main/about_us.html'

    def get(self, request, *args, **kwargs):
        context = {}
        context['title'] = 'About us'
        return render(request, self.template_name, context)


class ContactView(View):
    template_name = 'main/contact.html'

    def get(self, request, *args, **kwargs):
        context = {}
        context['title'] = 'Contact'
        return render(request, self.template_name, context)


class TestimonyView(View):
    template_name = 'main/testimony.html'

    def get(self, request, *args, **kwargs):
        context = {}
        context['title'] = 'Testimony'
        context['testimonies'] = Testimony.objects.all()
        return render(request, self.template_name, context)


class BlogView(View):
    template_name = 'main/blog.html'

    def get(self, request, *args, **kwargs):
        context = {}
        context['title'] = 'Information'
        context['posts'] = Article.objects.filter(
            active=True, belong_to__name='pwud')
        return render(request, self.template_name, context)


class HcwBlogView(View):
    template_name = 'main/hcw_blog.html'

    def get(self, request, *args, **kwargs):
        context = {}
        context['title'] = 'Health Care Worker Information'
        context['posts'] = Article.objects.filter(
            active=True, belong_to__name='hcw')
        return render(request, self.template_name, context)

class CountBlogView(View):
    def get(self, request, *args, **kwargs):

        obj = get_object_or_404(Article, pk=self.kwargs['pk'])

        view = obj.views
        view += 1

        obj.views = view
        obj.save()

        return HttpResponseRedirect(reverse('main:blog_detail', kwargs={'pk': self.kwargs['pk']}))

class BlogDetailView(DetailView):
    model = Article
    extra_context = {'title': 'Huru article'}


class HcwBlogDetailView(DetailView):
    template_name = 'main/hcw_article_detail.html'
    model = Article
    extra_context = {'title': 'Huru article'}


class CategoryDetailView(DetailView):
    model = Category
    extra_context = {'title': 'Huru category article'}


class HcwCategoryDetailView(DetailView):
    template_name = 'main/hcw_category_detail.html'
    model = Category
    extra_context = {'title': 'Huru category article'}


class ServiceView(View):
    template_name = 'main/services.html'

    def get(self, request, *args, **kwargs):

        # filter by keyword
        keyword = self.request.GET.get('keyword', '')
        queryset = Service.objects.all()
        if keyword:
            queryset = queryset.filter(Q(facility__icontains=keyword) | Q(
                facility_type__icontains=keyword))

        context = {}
        context['title'] = 'Services'
        context['services'] = queryset
        return render(request, self.template_name, context)


class TestimonyDetailView(DetailView):
    model = Testimony
    extra_context = {'title': 'Huru testimony'}


class PrivacyPolicy(View):
    template_name = 'main/privacy_policy.html'

    def get(self, request, *args, **kwargs):

        context = {}
        context['title'] = 'Privacy policy'
        return render(request, self.template_name, context)

templates/main/blog.html
{% extends 'master/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

{% get_current_language as LANGUAGE_CODE %}

<!-- Start Page Title Area -->
<div class="page-title-area page-title-style-three item-bg1 jarallax" data-jarallax='{"speed": 0.3}'>
    <div class="container">
        <div class="page-title-content">
            <ul>
                <li><a href="{% url 'main:home'  %}">{% trans 'Home' %}</a></li>
                <li>{% trans 'Information' %}</li>
            </ul>
            <h2>{% trans 'Posts' %}</h2>
        </div>
    </div>
</div>
<!-- End Page Title Area -->
    

<!-- Start Posts Area -->
<section class="courses-area pt-70 pb-70">
    <div class="container">
        <div class="section-title text-left">
            <h2>{% trans 'Our Popular Posts' %}</h2>
            {% if posts.count >= 10 %}
            <a href="" class="default-btn"><i class='bx bx-show-alt icon-arrow before'></i><span class="label">{% trans 'All Posts' %}</span><i class="bx bx-show-alt icon-arrow after"></i></a>
            {% endif %}
        </div>
        
        {% if posts.count != 0 %}
        <div class="shorting">
            <div class="row">

                {% for post in posts %}
                <div class="col-lg-4 col-md-6">
                    <div class="single-courses-box mb-30">
                        <div class="courses-image text-center">
                            <a href="{% url 'main:blog_detail' post.id %}" class="d-block"><img src="/media/{{post.cover_photo}}" alt="image"></a>

                            <div class="courses-tag">
                                <a href="{% url 'main:category_information' post.category_id %}" class="d-block">{{post.category}}</a>
                            </div>
                        </div>

                        <div class="courses-content">
                            
                            <h3><a href="{% url 'main:blog_detail' post.id %}" class="d-inline-block">{% if LANGUAGE_CODE == 'sw' %} {{post.sw_title|default_if_none:''}} {% else %} {{post.title}} {% endif %}</a></h3>

                            <div>
                                
                                {% if post.content|length > 300 %}
                            <a href="{% url 'main:blog_detail' post.id %}" class="read-more-btn">{% trans 'Read More' %} <i class='bx bx-right-arrow-alt'></i></a>
                            {% endif %}
                            </div>
                        </div>

                        <div class="courses-box-footer">
                            <ul>
                                <li class="">
                                    {% trans 'By' %}: <a href="#" class="d-inline-block">{{post.user.group}}</a>
                                </li>

                                <li class="">
                                    {{post.date_posted}}
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
        {%else%}

        <h5 class="text-center card" style="padding: 10px;">{% trans 'No Post' %}</h5>

        {% endif %}

    </div>
</section>
<!-- End Posts Area -->
{% endblock %}

templates/main/hcw_blog.html
{% extends 'master/hcw_base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<!-- Start Page Title Area -->
<div class="page-title-area page-title-style-three item-bg1 jarallax" data-jarallax='{"speed": 0.3}'>
    <div class="container">
        <div class="page-title-content">
            <ul>
                <li><a href="{% url 'main:home'  %}">{% trans 'Home' %}</a></li>
                <li>{% trans 'Information' %}</li>
            </ul>
            <h2>{% trans 'Posts' %}</h2>
        </div>
    </div>
</div>
<!-- End Page Title Area -->
    

<!-- Start Posts Area -->
<section class="courses-area pt-70 pb-70">
    <div class="container">
        <div class="section-title text-left">
            <h2>{% trans 'Our Popular Posts' %}</h2>
            {% if posts.count >= 10 %}
            <a href="" class="default-btn"><i class='bx bx-show-alt icon-arrow before'></i><span class="label">{% trans 'All Posts' %}</span><i class="bx bx-show-alt icon-arrow after"></i></a>
            {% endif %}
        </div>
        
        {% if posts.count != 0 %}
        <div class="shorting">
            <div class="row">

                {% for post in posts %}
                <div class="col-lg-4 col-md-6">
                    <div class="single-courses-box mb-30">
                        <div class="courses-image text-center">
                            <a href="{% url 'main:hcw_blog_detail' post.id %}" class="d-block"><img src="/media/{{post.cover_photo}}" alt="image"></a>

                            <div class="courses-tag">
                                <a href="{% url 'main:hcw_category_information' post.category_id %}" class="d-block">{{post.category}}</a>
                            </div>
                        </div>

                        <div class="courses-content">
                            
                            <h3><a href="{% url 'main:hcw_blog_detail' post.id %}" class="d-inline-block">{{post.title}}</a></h3>

                            <div>
                                
                                {% if post.content|length > 300 %}
                            <a href="{% url 'main:hcw_blog_detail' post.id %}" class="read-more-btn">{% trans 'Read More' %} <i class='bx bx-right-arrow-alt'></i></a>
                            {% endif %}
                            </div>
                        </div>

                        <div class="courses-box-footer">
                            <ul>
                                <li class="">
                                    {% trans 'By' %}: <a href="#" class="d-inline-block">{{post.user.group}}</a>
                                </li>

                                <li class="">
                                    {{post.date_posted}}
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
        {%else%}

        <h5 class="text-center card" style="padding: 10px;">{% trans 'No Post' %}</h5>

        {% endif %}

    </div>
</section>
<!-- End Posts Area -->
{% endblock %}

templates/main/home.html
{% extends 'master/base.html' %}
{% load static %}
{% load embed_video_tags %}
{% load i18n %}

{% block content %}

{% get_current_language as LANGUAGE_CODE %}

<!-- Start Main Banner -->
<section class="home-slides owl-carousel owl-theme">
    <div class="main-banner item-bg1" style="height: 600px;">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="main-banner-content text-center">
                        <span class="sub-title">{% trans 'You are not alone' %}</span>
                        <h1>{% trans 'Recovery is Possible' %}</h1>
                        <p>{% trans 'You can stop using drugs, you just have to make the decision to do so today.' %}</p>

                        <div class="btn-box">
                            <a href="{% url 'main:service_list' %}" class="default-btn"><i class='bx bx-move-horizontal icon-arrow before'></i><span class="label">{% trans 'search services' %}</span><i class="bx bx-move-horizontal icon-arrow after"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main-banner item-bg2" style="height: 600px;">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="main-banner-content text-center">
                        <span class="sub-title">{% trans 'You are not alone' %}</span>
                        <h1>{% trans 'Are you ready to get the real you back?' %}</h1>
                        <p>{% trans 'We will help you to find where you can go for treatment and other essential services' %}</p>
                        <div class="btn-box">
                            <a href="{% url 'main:service_list' %}" class="default-btn"><i class='bx bx-move-horizontal icon-arrow before'></i><span class="label">{% trans 'search services' %}</span><i class="bx bx-move-horizontal icon-arrow after"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main-banner item-bg3" style="height: 600px;">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="main-banner-content text-center">
                        <span class="sub-title">{% trans 'You are not alone' %}</span>
                        <h1>{% trans 'Addiction affects all communities' %}</h1>
                        <p>{% trans 'Making the decision to find a detox center or drug or alcohol rehab is the first step toward a new, healthy life.' %}</p>

                        <div class="btn-box">
                            <a href="{% url 'main:service_list' %}" class="default-btn"><i class='bx bx-move-horizontal icon-arrow before'></i><span class="label">{% trans 'search services' %}</span><i class="bx bx-move-horizontal icon-arrow after"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Main Banner -->


<!-- Start Posts Area -->
<section class="courses-area pt-70 pb-70">
    <div class="container">
        <div class="section-title text-left">
            <h2>{% trans 'Our Popular Posts' %}</h2>
            {% if posts.count >= 10 %}
            <a href="" class="default-btn"><i class='bx bx-show-alt icon-arrow before'></i><span class="label">{% trans 'All Posts' %}</span><i class="bx bx-show-alt icon-arrow after"></i></a>
            {% endif %}
        </div>

        {% if posts.count != 0 %}
        <div class="shorting">
            <div class="row">

                {% for post in posts %}
                <div class="col-lg-4 col-md-6">
                    <div class="single-courses-box mb-30">
                        <div class="courses-image text-center">
                            <a href="{% url 'main:count_blog' post.id %}" class="d-block"><img src="/media/{{post.cover_photo}}" alt="image"></a>

                            <div class="courses-tag">
                                <a href="{% url 'main:category_information' post.category_id %}" class="d-block">
                                  {% if LANGUAGE_CODE == 'en' %}

                                    {% if post.category != None %}
                                      {{post.category.name|default_if_none:''}}
                                    {% endif %}

                                  {% else %}

                                  {% if post.category != None %}
                                    {{post.category.sw_name|default_if_none:''}}
                                  {% endif %}

                                  {% endif %}
                                </a>
                            </div>
                        </div>

                        <div class="courses-content">

                            <h3><a href="{% url 'main:count_blog' post.id %}" class="d-inline-block">{% if LANGUAGE_CODE == 'sw' %} {{post.sw_title|default_if_none:''}} {% else %} {{post.title}} {% endif %}</a></h3>

                            <div>

                            {% if post.content|length > 300 %}
                            <a href="{% url 'main:count_blog' post.id %}" class="read-more-btn">{% trans 'Read More' %} <i class='bx bx-right-arrow-alt'></i></a>
                            {% endif %}
                            </div>
                        </div>

                        <div class="courses-box-footer">
                            <ul>
                                <li class="">
                                    {% trans 'By' %}: <a href="#" class="d-inline-block">{{post.user.group}}</a>
                                </li>

                                <li class="">
                                    {{post.date_posted}}
                                </li>

                                <li class="">
                                  <br/>
                                    Views {{post.views|default_if_none:'0'}}
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
        {%else%}

        <h5 class="text-center card" style="padding: 10px;">{% trans 'No Post' %}</h5>

        {% endif %}

    </div>
</section>
<!-- End Posts Area -->

<!-- testimony .start -->
<section class="blog-area pb-70">
    <div class="container">

        <div class="section-title text-left">
            <h2>{% trans 'Testimony' %}</h2>
            {% if testimonies.count >= 10 %}
            <a href="blog-style-1.html" class="default-btn"><i class='bx bx-show-alt icon-arrow before'></i><span
                    class="label">{% trans 'View All' %}</span><i class='bx bx-show-alt icon-arrow after'></i></a>
            {% endif %}
        </div>

        {% if testimonies.count != 0 %}

        <div class="shorting">
            <div class="row">

                {% for obj in testimonies %}
                <!-- testimony .start -->
                <div class="col-lg-4 col-md-6">
                    <div class="single-blog-post mb-30">
                        <div style="height: 200px; width: 100%;">
                            {% video obj.url '100% x 100%' %}
                        </div>

                        <div class="post-content">
                            <ul class="post-meta">
                                <li class="post-author">
                                    Date posted: <a href="javascript:void(0);" class="d-inline-block">{{obj.date_posted}}</a>
                                </li>
                            </ul>
                            <h3><a href="{% url 'main:testimony_detail' obj.id %}" class="d-inline-block">{{obj.title}}</a></h3>

                            {% if obj.content|length > 300 %}
                            <a href="{% url 'main:testimony_detail' obj.id %}" class="read-more-btn">Read More <i class='bx bx-right-arrow-alt'></i></a>
                            {% endif %}

                        </div>
                    </div>
                </div>
                <!-- testimony .end -->
                {% endfor %}

            </div>
        </div>
        {% else %}
        <h5 class="text-center card" style="padding: 10px;">{% trans 'No Testimony' %}</h5>
        {% endif %}

    </div>
</section>
<!-- testimony ./end -->




<!-- Start Funfacts Area -->
<section class="funfacts-area">
    <div class="container">
        <div class="funfacts-inner">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-6">
                    <div class="single-funfact">
                        <div class="icon">
                            <i class='bx bxs-building-house'></i>
                        </div>
                        <h3 class="odometer" data-count="{{service_number}}">00</h3>
                        <p>{% trans 'Available Services' %}</p>
                    </div>
                </div>

                <div class="col-lg-6 col-md-6 col-6">
                    <div class="single-funfact">
                        <div class="icon">
                            <i class='bx bx-book-reader'></i>
                        </div>
                        <h3 class="odometer" data-count="{{posts.count}}">00</h3>
                        <p>
                          <!-- {% trans 'Total Articles' %} -->

                          {% if LANGUAGE_CODE == 'en' %}
                          Total Articles
                          {% else %}
                          Jumla ya Nakala
                          {% endif %}
                        </p>
                    </div>
                </div>


                {% comment %}
                <div class="col-lg-4 col-md-4 col-6">
                    <div class="single-funfact">
                        <div class="icon">
                            <i class='bx bx-user-pin'></i>
                        </div>
                        <h3 class="odometer" data-count="8190">00</h3>
                        <p>Happy Customers</p>
                    </div>
                </div>
                {% endcomment %}


            </div>

            <div id="particles-js-circle-bubble"></div>
        </div>
    </div>
</section>
<!-- End Funfacts Area -->

{% endblock %}

templates/main/services.html
{% extends 'master/base.html' %}
{% load embed_video_tags %}
{% load static %}
{% load i18n %}


{% block content %}
<!-- Start Page Title Area -->
<div class="page-title-area page-title-style-three item-bg1 jarallax" data-jarallax='{"speed": 0.3}'>
    <div class="container">
        <div class="page-title-content">
            <ul>
                <li><a href="{% url 'main:home'  %}">{% trans 'Home' %}</a></li>
                <li>{% trans 'Find Services' %}</li>
            </ul>
            <h2>{% trans 'Services' %}</h2>
        </div>
    </div>
</div>
<!-- End Page Title Area -->

<!-- Start service Area -->
<section class="pricing-area ptb-100">
    <div class="container">

        <form action="" method="GET">
            <div class="input-group mb-3">
                <input type="text" class="form-control" name="keyword" value="{{request.GET.keyword}}" placeholder="Search facility or facility type">
                <div class="input-group-append">
                <button class="input-group-text">search</button>
                </div>
            </div>
        </form>

        {% if services.count != 0 %}
        <div class="pricing-table table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">{% trans 'Facility' %}</th>
                        <th scope="col">{% trans 'Facility-Type' %}</th>
                        <th scope="col">{% trans 'Service' %}</th>
                        <th scope="col">{% trans 'Contact' %}</th>
                        <th scope="col">{% trans 'Location' %}</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for service in services %}
                    <tr>
                        <td>{{service.facility}}</td>
                        <td>{{service.facility_type}}</td>
                        <td>{{service.service_offered|safe}}</td>
                        <td>{{service.contact}}</td>
                        <td>{{service.location}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <div class="row">
            <div class="col-md-12 card text-center" style="padding: 20px;">{% trans 'No Service' %}</div>
        </div>
        {% endif %}
            
    </div>
</section>
<!-- End service Area -->
    
{% endblock %}