app/huru_admin/urls.py
from django.urls import path
from . import views

app_name = 'huru_admin'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('article/', views.ArticleView.as_view(), name='article'),
    path('add/', views.AddArticle.as_view(), name='add_article'),
    path('testimony/', views.TestimonyView.as_view(), name='testimony_view'),
    path('add-testimony/', views.AddTestimonyView.as_view(), name='add_testimony'),
    path('service/', views.ServiceView.as_view(), name='service_view'),
    path('add-service/', views.AddServiceView.as_view(), name='add_service'),
]

app/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('hcw/', views.HCWHomeView.as_view(), name='hcw_home'),
    path('about-us/', views.AboutUsView.as_view(), name='about_us'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('testimony/', views.TestimonyView.as_view(), name='testimony'),
    path('blog/', views.BlogView.as_view(), name='blog'),
    path('hcw-blog/', views.HcwBlogView.as_view(), name='hcw_blog'),
    path('count-blog/<int:pk>/', views.CountBlogView.as_view(), name='count_blog'),
    path('blog-detail/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('hcw-blog-detail/<int:pk>/', views.HcwBlogDetailView.as_view(), name='hcw_blog_detail'),
    path('category-info/<int:pk>', views.CategoryDetailView.as_view(),
         name='category_information'),
     path('hcw-category-info/<int:pk>', views.HcwCategoryDetailView.as_view(),
         name='hcw_category_information'),
    path('services/', views.ServiceView.as_view(), name='service_list'),
    path('testimony-detail/<int:pk>/',
         views.TestimonyDetailView.as_view(), name='testimony_detail'),
    path('privacy-policy/', views.PrivacyPolicy.as_view(), name='privacy_policy'),
]

huru/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('', include('app.main.urls', namespace='main')),
    path('api/', include('app.main.api.urls', namespace='main_api')),
    path('auth/', include('app.user.urls')),
    path('admin/', include('app.huru_admin.urls')),
    path('super-admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Huru adminstration'
admin.site.site_title = 'Huru'

templates/includes/admin_chat.html
{% load static %}
<div class="chat-launcher"></div>
<div class="chat-wrapper">
    <div class="card">
        <div class="header">
            <ul class="list-unstyled team-info margin-0">
                <li class="m-r-15"><h2>Design Team</h2></li>
                <li>
                    <img src="{% static 'assets/images/xs/avatar2.jpg' %}" alt="Avatar">
                </li>
                <li>
                    <img src="{% static 'assets/images/xs/avatar3.jpg' %}" alt="Avatar">
                </li>
                <li>
                    <img src="{% static 'assets/images/xs/avatar4.jpg' %}" alt="Avatar">
                </li>
                <li>
                    <img src="{% static 'assets/images/xs/avatar6.jpg' %}" alt="Avatar">
                </li>
                <li>
                    <a href="javascript:void(0);" title="Add Member"><i class="zmdi zmdi-plus-circle"></i></a>
                </li>
            </ul>                       
        </div>
        <div class="body">
            <div class="chat-widget">
            <ul class="chat-scroll-list clearfix">
                <li class="left float-left">
                    <img src="{% static 'assets/images/xs/avatar3.jpg' %}" class="rounded-circle" alt="">
                    <div class="chat-info">
                        <a class="name" href="#">Alexander</a>
                        <span class="datetime">6:12</span>                            
                        <span class="message">Hello, John </span>
                    </div>
                </li>
                <li class="right">
                    <div class="chat-info"><span class="datetime">6:15</span> <span class="message">Hi, Alexander<br> How are you!</span> </div>
                </li>
                <li class="right">
                    <div class="chat-info"><span class="datetime">6:16</span> <span class="message">There are many variations of passages of Lorem Ipsum available</span> </div>
                </li>
                <li class="left float-left"> <img src="{% static 'assets/images/xs/avatar2.jpg' %}" class="rounded-circle" alt="">
                    <div class="chat-info"> <a class="name" href="#">Elizabeth</a> <span class="datetime">6:25</span> <span class="message">Hi, Alexander,<br> John <br> What are you doing?</span> </div>
                </li>
                <li class="left float-left"> <img src="{% static 'assets/images/xs/avatar1.jpg' %}" class="rounded-circle" alt="">
                    <div class="chat-info"> <a class="name" href="#">Michael</a> <span class="datetime">6:28</span> <span class="message">I would love to join the team.</span> </div>
                </li>
                    <li class="right">
                    <div class="chat-info"><span class="datetime">7:02</span> <span class="message">Hello, <br>Michael</span> </div>
                </li>
            </ul>
            </div>
            <div class="input-group p-t-15">
                <input type="text" class="form-control" placeholder="Enter text here...">
                <span class="input-group-addon">
                    <i class="zmdi zmdi-mail-send"></i>
                </span>
            </div>
        </div>
    </div>
</div>

templates/includes/admin_footer.html
{% load static %}
<script src="{% static 'assets/bundles/libscripts.bundle.js' %}"></script>
<!-- Lib Scripts Plugin Js ( jquery.v3.2.1, Bootstrap4 js) -->
<script src="{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script>
<!-- slimscroll, waves Scripts Plugin Js -->

<script src="{% static 'assets/bundles/morrisscripts.bundle.js' %}"></script><!-- Morris Plugin Js -->
<script src="{% static 'assets/bundles/jvectormap.bundle.js' %}"></script> <!-- JVectorMap Plugin Js -->
<script src="{% static 'assets/bundles/knob.bundle.js' %}"></script> <!-- Jquery Knob Plugin Js -->
<script src="{% static 'assets/bundles/sparkline.bundle.js' %}"></script> <!-- Sparkline Plugin Js -->

{% include "includes/alert_script.html" %}

{% comment %}
<script src="{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>

<script src="{% static 'assets/js/pages/index.js' %}"></script>
{% endcomment %}

templates/includes/admin_header.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <title>{{title}}</title>
    <link rel="icon" href="favicon.ico" type="image/x-icon"> <!-- Favicon-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/plugins/morrisjs/morris.min.css' %}" />
    <!-- Custom Css -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/color_skins.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

templates/includes/admin_preloader.html
{% load static %}
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="m-t-30"><img class="zmdi-hc-spin" src="{% static 'assets/images/logo.svg' %}" width="48" height="48" alt="loader"></div>
        <p>Please wait...</p>
    </div>
</div>

templates/includes/admin_sidebar.html
{% url 'huru_admin:home' as home  %}
{% url 'huru_admin:article' as article  %}
{% url 'huru_admin:add_article' as add_article  %}
{% url 'huru_admin:testimony_view' as testimony_view  %}
{% url 'huru_admin:add_testimony' as add_testimony  %}
{% url 'huru_admin:service_view' as service_view  %}
{% url 'huru_admin:add_service' as add_service  %}

{% load static %}
<aside id="leftsidebar" class="sidebar">
    <div class="menu">
        <ul class="list">
            <li>
                <div class="user-info">
                    <div class="image"><a href="profile.html"><img src="{% static 'assets/images/user1.png' %}"
                                alt="User"></a></div>
                    <div class="detail" style="padding-bottom: 10px;">
                        <h4 class="text-uppercase">{{request.user}}</h4>
                        <small>{{request.user.group}}</small>
                    </div>
                    
                </div>
            </li>
            <li class="header">MAIN</li>
            <li class="{% if request.path == home %}active{% endif %}"> <a href="{% url 'huru_admin:home' %}"><i
                        class="zmdi zmdi-home"></i><span>Dashboard</span></a>
            </li>
            <li class="header">CONTENTS</li>
            <li class="{% if request.path == article or request.path == add_article %}active{% endif %}"> <a
                    href="{% url 'huru_admin:article'  %}"><i class="zmdi zmdi-assignment"></i><span>Article</span> </a>
            </li>
            <li class="{% if request.path == testimony_view or request.path == add_testimony %}active{% endif %}"> <a href="{% url 'huru_admin:testimony_view'  %}"><i class="zmdi zmdi-grid"></i><span>Testimony</span></a></li>
            <li class="{% if request.path == service_view or request.path == add_service %}active{% endif %}"> <a href="{% url 'huru_admin:service_view'  %}"><i class="zmdi zmdi-view-list"></i><span>Service</span></a></li>
            
            <li class="header">HURU USERS</li>
            <li> <a href="javascript:void(0);"><i class="zmdi zmdi-accounts"></i><span>Users</span> </a>

            </li>
        </ul>
    </div>
</aside>

templates/includes/alert.html
<div class="alert wrong_account" style="display: none;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <i class="icofont icofont-close-line-circled"></i>
    </button>
    <span class="msg"></span>
</div>

templates/includes/alert_script.html
<script>
    $(document).ready(function () {
        var message = '{%for msg in messages%}{{ msg }}{% endfor %}';
        var message_tag = '{% for msg in messages %}{{ msg.tags }}{% endfor %}';

        msg_tag = "";
        if (message_tag == 'error') {
        msg_tag = "alert-danger";
        } else if (message_tag == 'success') {
        msg_tag = "alert-success";
        }
        if (message != '') {
        $('.alert').addClass(msg_tag);
            $('.msg').html(message);
            $('.wrong_account').delay(50).slideDown(350);
            $('.wrong_account').delay(4000).slideUp();
        }

        $('.errorlist').removeClass('alert alert-danger').addClass('text-danger');
    });
</script>

templates/includes/bloc_header.html
<div class="block-header">
    <div class="row">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <h2>{{page_title}}
                <small class="text-muted">Welcome to Huru</small>
            </h2>
        </div>
        <div class="col-lg-5 col-md-6 col-sm-12">
            {% if page_title == 'article' %}
            <a href="{% url 'huru_admin:add_article' %}" class="btn btn-info btn-sm float-md-right">ADD-ARTICLE</a>
            {% elif page_title == 'testimony' %}
            <a href="{% url 'huru_admin:add_testimony'  %}" class="btn btn-info btn-sm float-md-right">ADD-TESTIMONY</a>
            {% elif page_title == 'service' %}
            <a href="{% url 'huru_admin:add_service'  %}" class="btn btn-info btn-sm float-md-right">ADD-SERVICE</a>
            {% else %}
            <ul class="breadcrumb float-md-right">
                <li class="breadcrumb-item"><a href="{% url 'huru_admin:home'  %}"><i class="zmdi zmdi-home"></i>
                        Huru</a>
                </li>
                <li class="breadcrumb-item active">{{page_title}}</li>
            </ul>
            {% endif %}
        </div>
    </div>
</div>

templates/includes/footer.html
{% load static %}
<!-- Jquery JS -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<!-- Popper JS -->
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<!-- Owl Carousel JS -->
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<!-- Mixitup JS -->
<script src="{% static 'assets/js/mixitup.min.js' %}"></script>
<!-- Parallax JS -->
<script src="{% static 'assets/js/parallax.min.js' %}"></script>
<!-- Appear JS -->
<script src="{% static 'assets/js/jquery.appear.min.js' %}"></script>
<!-- Odometer JS -->
<script src="{% static 'assets/js/odometer.min.js' %}"></script>
<!-- Particles JS -->
<script src="{% static 'assets/js/particles.min.js' %}"></script>
<!-- MeanMenu JS -->
<script src="{% static 'assets/js/meanmenu.min.js' %}"></script>
<!-- Nice Select JS -->
<script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
<!-- Viewer JS -->
<script src="{% static 'assets/js/viewer.min.js' %}"></script>
<!-- Slick JS -->
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<!-- Magnific Popup JS -->
<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
<!-- AjaxChimp JS -->
<script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>
<!-- Form Validator JS -->
<script src="{% static 'assets/js/form-validator.min.js' %}"></script>
<!-- Contact Form JS -->
<script src="{% static 'assets/js/contact-form-script.js' %}"></script>
<!-- Raque Map JS -->
<script src="{% static 'assets/js/raque-map.js' %}"></script>
<!-- Main JS -->
<script src="{% static 'assets/js/main.js' %}"></script>


<!-- Slider Revolution core JavaScript files -->
<script src="{% static 'assets/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/extensionshemepunch.revolutio.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/extensions/revolution.extension.carousel.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
<script src="{% static 'assets/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
<script src="{% static 'assets/js/rev-slider-custom.js' %}"></script>

templates/includes/footer_text.html
{% load static %}
{% load i18n %}
<!-- Start Footer Area -->
<footer class="footer-area" style="padding: 0px;">
    <div class="footer-bottom-area">
        <div class="container">

            <div class="row align-items-center">
                <div class="col-lg-12 col-md-12" style="padding-bottom: 10px;">

                    {% get_current_language as LANGUAGE_CODE %}

                    <div class="language-switcher d-inline-block">
                        <form action="{% url 'set_language' %}" method="POST">
                            <div class=" language-switcher d-inline-block">

                                    {% csrf_token %}
                                    <input name="next" type="hidden" value="{{ redirect_to }}">
                                    <select name="language" id="">
                                        {% get_available_languages as LANGUAGES %}
                                        {% get_language_info_list for LANGUAGES as languages %}

                                        {% for language in languages %}
                                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                                {{ language.name_local }} ({{ language.code }})
                                            </option>
                                        {% endfor %}
                                    </select>
                            </div>
                            <input type="submit" class="btn btn-light" value="change" style="color: black;">
                        </form>
                    </div>

                    <div class="search-box d-inline-block" style="visibility: hidden;">
                        <i class='bx bx-search'></i>
                    </div>
                </div>
            </div>

            <div class="logo">
                <a href="javascript:void(0);" class="d-inline-block">
                    <img src="{% static 'assets/img/new_logo.png' %}" alt="image">
                    </a>
            </div>

            <p>{% trans 'Copyright' %} <i class='bx bx-copyright'></i>{% now 'Y' %} {% trans 'Huru All Rights Reserved.' %}
            </p>
            <a class="btn btn-secondary" href="https://play.google.com/store/apps/details?id=com.huruapp.huruapp" target="_blank"><p><span class="text-white"><i class="fa fa-android" style="font-size: 20px;"></i> Download on Playstore</span></div></p></a>

            <p><a href="{% url 'main:privacy_policy'  %}" target="_blank">Huruapp Privacy Policy</a></p>
        </div>
    </div>
</footer>
<!-- End Footer Area -->

templates/includes/header.html
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Revolution Slider CSS -->
    <link rel="stylesheet" href="{% static 'assets/revolution/css/settings.css' %}">
    <link rel="stylesheet" href="{% static 'assets/revolution/css/layers.css' %}">
    <link rel="stylesheet" href="{% static 'assets/revolution/css/navigation.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap..min.css' %}">
    <!-- BoxIcons CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/boxicons.min.css' %}">
    <!-- Owl Carousel CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <!-- Odometer CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/odometer.min.css' %}">
    <!-- MeanMenu CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <!-- Nice Select CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.min.css' %}">
    <!-- Viewer CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/viewer.min.css' %}">
    <!-- Slick CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/slick.min.css' %}">
    <!-- Magnific Popup CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.min.css' %}">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{{title}}</title>

    <!-- <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}"> -->
</head>

templates/includes/menu.html
{% load static %}
{% load i18n %}

{% url 'main:home' as home  %}
{% url 'main:hcw_home' as hcw_home  %}
{% url 'main:about_us' as about_us %}
{% url 'main:contact' as contact %}
{% url 'main:testimony' as testimony %}
{% url 'main:blog' as blog %}
{% url 'main:category_information' as category_information %}
{% url 'main:service_list' as service_list %}
{% url 'main:blog_detail' object.id as blog_detail %}
{% url 'main:category_information' object.id as category_information %}


<!-- Start Header Area -->
<header class="header-area p-relative">

    <!-- <div class="top-header top-header-style-four"> 
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 col-md-12" style="padding: 10px;">
                    <ul class="top-header-login-register">
                        <li><a href="{% url 'main:hcw_home' %}"><i class='bx bx-log-in-circle'></i> {% trans 'Huru for Healthcare Workers' %}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div> -->

    <!-- Start Navbar Area -->
    <div class="navbar-area navbar-style-three">
        <div class="raque-responsive-nav">
            <div class="container">
                <div class="raque-responsive-menu">
                    <div class="logo">
                        <a href="{% url 'main:home'  %}">
                            <img src="{% static 'assets/img/new_huru_logo.jpg' %}" style="height: 45px;" alt="logo">
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="raque-nav">
            <div class="container">
                <nav class="navbar navbar-expand-md navbar-light">
                    <a class="navbar-brand" href="{% url 'main:home'  %}">
                        <img src="{% static 'assets/img/new_huru_logo.jpg' %}" style="height: 45px;" alt="logo">
                    </a>

                    <div class="collapse navbar-collapse mean-menu">
                        <ul class="navbar-nav">
                            <li class="nav-item"><a href="{% url 'main:home'  %}"
                                    class="nav-link {% if request.path == home %}active{% endif %}">{% trans 'Home' %}</a></li>

                            <li class="nav-item"><a href="{% url 'main:blog' %}"
                                    class="nav-link {% if request.path == blog or request.path == blog_detail or request.path == category_information %}active{% endif %}">{% trans 'Information' %}</a></li>

                            <li class="nav-item"><a href="{% url 'main:testimony' %}"
                                    class="nav-link {% if request.path == testimony %}active{% endif %}">{% trans 'Testimonies' %}</a>
                            </li>
                            <li class="nav-item"><a href="{% url 'main:service_list' %}" class="nav-link {% if request.path == service_list %}active{% endif %}">{% trans 'Find Services' %}</a></li>
                            <li class="nav-item"><a href="{% url 'main:about_us' %}"
                                    class="nav-link {% if request.path == about_us %}active{% endif %}">{% trans 'About Us' %} </a>
                            </li>
                        </ul>

                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- End Navbar Area -->

    <!-- Start Sticky Navbar Area -->
    <div class="navbar-area navbar-style-three header-sticky">
        <div class="raque-nav">
            <div class="container">
                <nav class="navbar navbar-expand-md navbar-light">
                    <a class="navbar-brand" href="{% url 'main:home' %}">
                        <img src="{% static 'assets/img/new_huru_logo.jpg' %}" style="height: 45px;" alt="logo">
                    </a>

                    <div class="collapse navbar-collapse">
                        <ul class="navbar-nav">
                            <li class="nav-item"><a href="{% url 'main:home'  %}"
                                    class="nav-link {% if request.path == home %}active{% endif %}">{% trans 'Home' %}</a></li>

                            <li class="nav-item"><a href="{% url 'main:blog' %}"
                                    class="nav-link {% if request.path == blog %}active{% endif %}">{% trans 'Information' %}</a></li>

                            <li class="nav-item"><a href="{% url 'main:testimony' %}"
                                    class="nav-link {% if request.path == testimony %}active{% endif %}">{% trans 'Testimonies' %}</a>
                            </li>
                            <li class="nav-item"><a href="{% url 'main:service_list' %}" class="nav-link {% if request.path == service_list %}active{% endif %}">{% trans 'Find Services' %}</a></li>
                            <li class="nav-item"><a href="{% url 'main:about_us' %}"
                                    class="nav-link {% if request.path == about_us %}active{% endif %}">{% trans 'About Us' %} </a>
                            </li>

                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- End Sticky Navbar Area -->

</header>
<!-- End Header Area -->

templates/includes/preloader.html
<!-- Preloader -->
<div class="preloader">
    <div class="loader">
        <div class="shadow"></div>
        <div class="box"></div>
    </div>
</div>
<!-- End Preloader -->

templates/includes/search.html
<!-- search-box-layout -->
<div class="search-overlay">
    <div class="d-table">
        <div class="d-table-cell">
            <div class="search-overlay-layer"></div>
            <div class="search-overlay-layer"></div>
            <div class="search-overlay-layer"></div>

            <div class="search-overlay-close">
                <span class="search-overlay-close-line"></span>
                <span class="search-overlay-close-line"></span>
            </div>

            <div class="search-overlay-form">
                <form>
                    <input type="text" class="input-search" placeholder="Search here...">
                    <button type="submit"><i class='bx bx-search-alt'></i></button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- search-box-layout end -->